title: eWPTXV2 Blog de la certificaci贸n
description: Este Blog se centra en la resoluci贸n y explotaci贸n de cada uno de los ataques que la certificaci贸n eWPTXV2 explica en sus laboratorios
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
